# -*- coding: utf-8 -*-
"""Testing Librosa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IiHKhAy7PLIMir6ILY0ihe5XOV5fzUKm
"""

# Beat tracking example

import librosa


# 1. Get the file path to an included audio example

filename = librosa.example('nutcracker')

# 2. Load the audio as a waveform `y`

#    Store the sampling rate as `sr`

y, sr = librosa.load(filename)

# 3. Run the default beat tracker

tempo, beat_frames = librosa.beat.beat_track(y=y, sr=sr)

print('Estimated tempo: {:.2f} beats per minute'.format(tempo))

# 4. Convert the frame indices of beat events into timestamps

beat_times = librosa.frames_to_time(beat_frames, sr=sr)
print(beat_times)

# Feature extraction example

import numpy as np

import librosa


# Load the example clip

y, sr = librosa.load(librosa.ex('nutcracker'))


# Set the hop length; at 22050 Hz, 512 samples ~= 23ms

hop_length = 512


# Separate harmonics and percussives into two waveforms

y_harmonic, y_percussive = librosa.effects.hpss(y)


# Beat track on the percussive signal

tempo, beat_frames = librosa.beat.beat_track(y=y_percussive,

                                             sr=sr)


# Compute MFCC features from the raw signal

mfcc = librosa.feature.mfcc(y=y, sr=sr, hop_length=hop_length, n_mfcc=13)


# And the first-order differences (delta features)

mfcc_delta = librosa.feature.delta(mfcc)


# Stack and synchronize between beat events

# This time, we'll use the mean value (default) instead of median

beat_mfcc_delta = librosa.util.sync(np.vstack([mfcc, mfcc_delta]),

                                    beat_frames)


# Compute chroma features from the harmonic signal

chromagram = librosa.feature.chroma_cqt(y=y_harmonic,

                                        sr=sr)


# Aggregate chroma features between beat events

# We'll use the median value of each feature between beat frames

beat_chroma = librosa.util.sync(chromagram,

                                beat_frames,

                                aggregate=np.median)


# Finally, stack all beat-synchronous features together

beat_features = np.vstack([beat_chroma, beat_mfcc_delta])

